import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        primary: '#004ac6',
        'primary-container': '#2563eb',
        secondary: '#006c49',
        tertiary: '#784b00',
        error: '#ba1a1a',
        surface: '#faf8ff',
        'on-surface': '#131b2e',
        'on-surface-variant': '#434655',
        // Extended design system colors from prototype
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'surface-variant': '#dae2fd',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-tint': '#0053db',
        'background': '#faf8ff',
        'on-background': '#131b2e',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#eeefff',
        'on-secondary-container': '#00714d',
        'on-tertiary-container': '#ffeedd',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#eef0ff',
        'inverse-surface': '#283044',
        'inverse-primary': '#b4c5ff',
        'outline': '#737686',
        'outline-variant': '#c3c6d7',
        'error-container': '#ffdad6',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
    },
  },
  plugins: [],
};

export default config;
