import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
    './src/lib/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#003DA6',
        'primary-container': '#0052D9',
        secondary: '#2D50CD',
        'secondary-fixed': '#DDE1FF',
        'on-secondary-fixed': '#001354',
        'on-secondary-fixed-variant': '#0737B8',
        tertiary: '#394851',
        'tertiary-fixed': '#D4E5F0',
        error: '#BA1A1A',
        surface: '#F8F9FF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#EEF4FF',
        'surface-container': '#E5EEFF',
        'surface-container-high': '#DBE9FF',
        'surface-container-highest': '#D5E4FA',
        'surface-variant': '#D5E4FA',
        'surface-dim': '#CDDBF1',
        'surface-bright': '#F8F9FF',
        'surface-tint': '#0353DA',
        'tertiary-container': '#506069',
        'on-surface': '#0E1C2C',
        'on-surface-variant': '#434654',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#CBD6FF',
        'on-secondary': '#FFFFFF',
        'on-secondary-container': '#FFFBFF',
        'on-tertiary': '#FFFFFF',
        'on-tertiary-fixed': '#0D1D25',
        'on-tertiary-fixed-variant': '#394952',
        'on-tertiary-container': '#C9DAE5',
        'on-error': '#FFFFFF',
        'on-error-container': '#93000A',
        background: '#F8F9FF',
        'on-background': '#0E1C2C',
        outline: '#737686',
        'outline-variant': '#C3C6D7',
        'inverse-surface': '#243142',
        'inverse-on-surface': '#EAF1FF',
        'inverse-primary': '#B4C5FF',
        'error-container': '#FFDAD6',
        'primary-fixed': '#DBE1FF',
        'primary-fixed-dim': '#B4C5FF',
        'on-primary-fixed': '#00174B',
        'on-primary-fixed-variant': '#003EA8',
        'secondary-fixed-dim': '#B8C4FF',
        'tertiary-fixed-dim': '#B8C9D3',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};

export default config;