COMMENT ON TABLE public.position_type IS '职位类型树表：存储岗位类别层级（一级/二级/三级）';
COMMENT ON COLUMN public.position_type.id IS '主键ID';
COMMENT ON COLUMN public.position_type.code IS '职位类型业务编码（外部同步编码）';
COMMENT ON COLUMN public.position_type.name IS '职位类型名称';
COMMENT ON COLUMN public.position_type.parent_id IS '父级职位类型ID（根节点为NULL）';
COMMENT ON COLUMN public.position_type.level IS '层级：1-一级 2-二级 3-三级';
COMMENT ON COLUMN public.position_type.sort_no IS '同级排序号';
COMMENT ON COLUMN public.position_type.status IS '状态：0-禁用 1-启用';
COMMENT ON COLUMN public.position_type.create_time IS '创建时间';
COMMENT ON COLUMN public.position_type.update_time IS '更新时间';
COMMENT ON COLUMN public.position_type.deleted IS '软删除标记：0-未删除 1-已删除';
